name: Sphinx Publish

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip
      - name: Get pip cache directory
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"
      - name: Pip cache dir operations
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get install graphviz
      - name: Build Sphinx HTML
        run: |
          cd docs/
          sphinx-build -M html . _build -D language=en
          sphinx-build -b html . _build/html/zh -D language=zh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html/

      
